# Generated by Django 4.2.1 on 2023-05-17 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0006_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.IntegerField(choices=[('new', 'New'), ('sale', 'Sale')], default='new'),
        ),
    ]
